IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LibraryItems')
BEGIN
    CREATE TABLE LibraryItems (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT NOT NULL,
        BookId INT NOT NULL,
        AddedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT FK_LibraryItems_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
        CONSTRAINT FK_LibraryItems_Books FOREIGN KEY (BookId) REFERENCES Books(Id) ON DELETE CASCADE
    );
    CREATE UNIQUE INDEX IX_LibraryItems_User_Book ON LibraryItems(UserId, BookId);
END
